// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: badgerItem.proto

package pbs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Ver64         uint64                 `protobuf:"varint,3,opt,name=ver64,proto3" json:"ver64,omitempty"`
	Sum64         uint64                 `protobuf:"varint,4,opt,name=sum64,proto3" json:"sum64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_badgerItem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_badgerItem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_badgerItem_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Item) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Item) GetVer64() uint64 {
	if x != nil {
		return x.Ver64
	}
	return 0
}

func (x *Item) GetSum64() uint64 {
	if x != nil {
		return x.Sum64
	}
	return 0
}

// The response message containing the greetings
type ItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errcode       int32                  `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Status        []byte                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Key           []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Ver64         uint64                 `protobuf:"varint,5,opt,name=ver64,proto3" json:"ver64,omitempty"`
	Sum64         uint64                 `protobuf:"varint,6,opt,name=sum64,proto3" json:"sum64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemReply) Reset() {
	*x = ItemReply{}
	mi := &file_badgerItem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReply) ProtoMessage() {}

func (x *ItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_badgerItem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReply.ProtoReflect.Descriptor instead.
func (*ItemReply) Descriptor() ([]byte, []int) {
	return file_badgerItem_proto_rawDescGZIP(), []int{1}
}

func (x *ItemReply) GetErrcode() int32 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *ItemReply) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ItemReply) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ItemReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ItemReply) GetVer64() uint64 {
	if x != nil {
		return x.Ver64
	}
	return 0
}

func (x *ItemReply) GetSum64() uint64 {
	if x != nil {
		return x.Sum64
	}
	return 0
}

type ListFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Pagenum       int32                  `protobuf:"varint,2,opt,name=pagenum,proto3" json:"pagenum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilter) Reset() {
	*x = ListFilter{}
	mi := &file_badgerItem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilter) ProtoMessage() {}

func (x *ListFilter) ProtoReflect() protoreflect.Message {
	mi := &file_badgerItem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilter.ProtoReflect.Descriptor instead.
func (*ListFilter) Descriptor() ([]byte, []int) {
	return file_badgerItem_proto_rawDescGZIP(), []int{2}
}

func (x *ListFilter) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListFilter) GetPagenum() int32 {
	if x != nil {
		return x.Pagenum
	}
	return 0
}

type ListFilterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilterReply) Reset() {
	*x = ListFilterReply{}
	mi := &file_badgerItem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilterReply) ProtoMessage() {}

func (x *ListFilterReply) ProtoReflect() protoreflect.Message {
	mi := &file_badgerItem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilterReply.ProtoReflect.Descriptor instead.
func (*ListFilterReply) Descriptor() ([]byte, []int) {
	return file_badgerItem_proto_rawDescGZIP(), []int{3}
}

func (x *ListFilterReply) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_badgerItem_proto protoreflect.FileDescriptor

const file_badgerItem_proto_rawDesc = "" +
	"\n" +
	"\x10badgerItem.proto\"X\n" +
	"\x04Item\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05ver64\x18\x03 \x01(\x04R\x05ver64\x12\x14\n" +
	"\x05sum64\x18\x04 \x01(\x04R\x05sum64\"\x8f\x01\n" +
	"\tItemReply\x12\x18\n" +
	"\aerrcode\x18\x01 \x01(\x05R\aerrcode\x12\x16\n" +
	"\x06status\x18\x02 \x01(\fR\x06status\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x14\n" +
	"\x05ver64\x18\x05 \x01(\x04R\x05ver64\x12\x14\n" +
	"\x05sum64\x18\x06 \x01(\x04R\x05sum64\">\n" +
	"\n" +
	"ListFilter\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x18\n" +
	"\apagenum\x18\x02 \x01(\x05R\apagenum\"%\n" +
	"\x0fListFilterReply\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys2\xc6\x01\n" +
	"\x06Badger\x12\x1a\n" +
	"\x03Get\x12\x05.Item\x1a\n" +
	".ItemReply\"\x00\x12\x1a\n" +
	"\x03Set\x12\x05.Item\x1a\n" +
	".ItemReply\"\x00\x12\x1d\n" +
	"\x06Delete\x12\x05.Item\x1a\n" +
	".ItemReply\"\x00\x12\x1d\n" +
	"\x06Exists\x12\x05.Item\x1a\n" +
	".ItemReply\"\x00\x12\x1d\n" +
	"\x06Status\x12\x05.Item\x1a\n" +
	".ItemReply\"\x00\x12'\n" +
	"\x04List\x12\v.ListFilter\x1a\x10.ListFilterReply\"\x00B Z\x1egithub.com/harryzhu/zstdfs/pbsb\x06proto3"

var (
	file_badgerItem_proto_rawDescOnce sync.Once
	file_badgerItem_proto_rawDescData []byte
)

func file_badgerItem_proto_rawDescGZIP() []byte {
	file_badgerItem_proto_rawDescOnce.Do(func() {
		file_badgerItem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_badgerItem_proto_rawDesc), len(file_badgerItem_proto_rawDesc)))
	})
	return file_badgerItem_proto_rawDescData
}

var file_badgerItem_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_badgerItem_proto_goTypes = []any{
	(*Item)(nil),            // 0: Item
	(*ItemReply)(nil),       // 1: ItemReply
	(*ListFilter)(nil),      // 2: ListFilter
	(*ListFilterReply)(nil), // 3: ListFilterReply
}
var file_badgerItem_proto_depIdxs = []int32{
	0, // 0: Badger.Get:input_type -> Item
	0, // 1: Badger.Set:input_type -> Item
	0, // 2: Badger.Delete:input_type -> Item
	0, // 3: Badger.Exists:input_type -> Item
	0, // 4: Badger.Status:input_type -> Item
	2, // 5: Badger.List:input_type -> ListFilter
	1, // 6: Badger.Get:output_type -> ItemReply
	1, // 7: Badger.Set:output_type -> ItemReply
	1, // 8: Badger.Delete:output_type -> ItemReply
	1, // 9: Badger.Exists:output_type -> ItemReply
	1, // 10: Badger.Status:output_type -> ItemReply
	3, // 11: Badger.List:output_type -> ListFilterReply
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_badgerItem_proto_init() }
func file_badgerItem_proto_init() {
	if File_badgerItem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_badgerItem_proto_rawDesc), len(file_badgerItem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_badgerItem_proto_goTypes,
		DependencyIndexes: file_badgerItem_proto_depIdxs,
		MessageInfos:      file_badgerItem_proto_msgTypes,
	}.Build()
	File_badgerItem_proto = out.File
	file_badgerItem_proto_goTypes = nil
	file_badgerItem_proto_depIdxs = nil
}
