// Code generated by protoc-gen-go. DO NOT EDIT.
// source: volume.proto

package volume

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_498b213ad3bcd5ad, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Message struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=Action,proto3" json:"Action,omitempty"`
	ErrCode              int32    `protobuf:"varint,4,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	Time                 string   `protobuf:"bytes,5,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_498b213ad3bcd5ad, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Message) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Message) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "volume.Empty")
	proto.RegisterType((*Message)(nil), "volume.Message")
}

func init() { proto.RegisterFile("volume.proto", fileDescriptor_498b213ad3bcd5ad) }

var fileDescriptor_498b213ad3bcd5ad = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x31, 0x6d, 0x12, 0x38, 0x8a, 0x80, 0x1b, 0x90, 0xc5, 0x14, 0x65, 0xf2, 0x14, 0x15,
	0x18, 0x99, 0x50, 0x29, 0xaa, 0x84, 0x58, 0x1c, 0xc4, 0x6e, 0xe2, 0x13, 0xb5, 0xb0, 0xe3, 0xca,
	0x75, 0x2b, 0xf5, 0xe7, 0xf2, 0x4f, 0x50, 0x4d, 0xba, 0x74, 0xca, 0xf6, 0xde, 0xe9, 0xbd, 0xd3,
	0xa7, 0x07, 0x93, 0xad, 0xb7, 0x1b, 0x47, 0xf5, 0x2a, 0xf8, 0xe8, 0x31, 0xff, 0x77, 0x55, 0x01,
	0xd9, 0xdc, 0xad, 0xe2, 0xae, 0xda, 0x40, 0xf1, 0x4e, 0xeb, 0xb5, 0xfa, 0x26, 0xbc, 0x86, 0xd1,
	0x1b, 0xed, 0x38, 0x2b, 0x99, 0x98, 0xc8, 0xbd, 0x44, 0x84, 0xf1, 0x8b, 0x8a, 0x8a, 0x9f, 0xa6,
	0x53, 0xd2, 0x78, 0x0b, 0xf9, 0x73, 0x1b, 0x8d, 0xef, 0xf8, 0xa8, 0x64, 0xe2, 0x5c, 0xf6, 0x0e,
	0x39, 0x14, 0xf3, 0x10, 0x66, 0x5e, 0x13, 0x1f, 0x97, 0x4c, 0x64, 0xf2, 0x60, 0xf7, 0x5f, 0x3e,
	0x8c, 0x23, 0x9e, 0xa5, 0x7c, 0xd2, 0x0f, 0xbf, 0x0c, 0x2e, 0x3f, 0x13, 0x4a, 0x43, 0x61, 0x6b,
	0x5a, 0xc2, 0x7b, 0xb8, 0x58, 0x90, 0xb2, 0x71, 0x39, 0x5b, 0x52, 0xfb, 0x83, 0x57, 0x75, 0xcf,
	0xdd, 0xd3, 0xdd, 0x1d, 0x1f, 0xaa, 0x13, 0xac, 0xe1, 0x4c, 0x92, 0xd2, 0xaf, 0xc6, 0xd2, 0xa0,
	0xfc, 0x14, 0x60, 0xa1, 0x3a, 0x6d, 0x69, 0x70, 0xe3, 0x09, 0x6e, 0x9a, 0x18, 0x48, 0xb9, 0x86,
	0x3a, 0x7d, 0xd8, 0x69, 0x40, 0x51, 0xb0, 0x29, 0xfb, 0xca, 0xd3, 0xe4, 0x8f, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc9, 0x30, 0x93, 0x39, 0x82, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VolumeServiceClient is the client API for VolumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VolumeServiceClient interface {
	HealthCheck(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	ReadFile(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	HandleFile(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	StreamSendMessage(ctx context.Context, opts ...grpc.CallOption) (VolumeService_StreamSendMessageClient, error)
}

type volumeServiceClient struct {
	cc *grpc.ClientConn
}

func NewVolumeServiceClient(cc *grpc.ClientConn) VolumeServiceClient {
	return &volumeServiceClient{cc}
}

func (c *volumeServiceClient) HealthCheck(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/volume.VolumeService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) ReadFile(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/volume.VolumeService/ReadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) HandleFile(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/volume.VolumeService/HandleFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) StreamSendMessage(ctx context.Context, opts ...grpc.CallOption) (VolumeService_StreamSendMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VolumeService_serviceDesc.Streams[0], "/volume.VolumeService/StreamSendMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &volumeServiceStreamSendMessageClient{stream}
	return x, nil
}

type VolumeService_StreamSendMessageClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type volumeServiceStreamSendMessageClient struct {
	grpc.ClientStream
}

func (x *volumeServiceStreamSendMessageClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *volumeServiceStreamSendMessageClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VolumeServiceServer is the server API for VolumeService service.
type VolumeServiceServer interface {
	HealthCheck(context.Context, *Message) (*Message, error)
	ReadFile(context.Context, *Message) (*Message, error)
	HandleFile(context.Context, *Message) (*Message, error)
	StreamSendMessage(VolumeService_StreamSendMessageServer) error
}

func RegisterVolumeServiceServer(s *grpc.Server, srv VolumeServiceServer) {
	s.RegisterService(&_VolumeService_serviceDesc, srv)
}

func _VolumeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume.VolumeService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).HealthCheck(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume.VolumeService/ReadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).ReadFile(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_HandleFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).HandleFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume.VolumeService/HandleFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).HandleFile(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_StreamSendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VolumeServiceServer).StreamSendMessage(&volumeServiceStreamSendMessageServer{stream})
}

type VolumeService_StreamSendMessageServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type volumeServiceStreamSendMessageServer struct {
	grpc.ServerStream
}

func (x *volumeServiceStreamSendMessageServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *volumeServiceStreamSendMessageServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _VolumeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "volume.VolumeService",
	HandlerType: (*VolumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _VolumeService_HealthCheck_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _VolumeService_ReadFile_Handler,
		},
		{
			MethodName: "HandleFile",
			Handler:    _VolumeService_HandleFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSendMessage",
			Handler:       _VolumeService_StreamSendMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "volume.proto",
}
