// Code generated by protoc-gen-go. DO NOT EDIT.
// source: volume.proto

package volume_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_498b213ad3bcd5ad, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Pong struct {
	Factor               string   `protobuf:"bytes,1,opt,name=Factor,proto3" json:"Factor,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_498b213ad3bcd5ad, []int{1}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetFactor() string {
	if m != nil {
		return m.Factor
	}
	return ""
}

func (m *Pong) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type File struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Meta                 []byte   `protobuf:"bytes,2,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_498b213ad3bcd5ad, []int{2}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *File) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "volume_pb.Empty")
	proto.RegisterType((*Pong)(nil), "volume_pb.Pong")
	proto.RegisterType((*File)(nil), "volume_pb.File")
}

func init() { proto.RegisterFile("volume.proto", fileDescriptor_498b213ad3bcd5ad) }

var fileDescriptor_498b213ad3bcd5ad = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xcb, 0xcf, 0x29,
	0xcd, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0xf0, 0xe2, 0x0b, 0x92, 0x94,
	0xd8, 0xb9, 0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0x2c, 0xb8, 0x58, 0x02, 0xf2, 0xf3, 0xd2,
	0x85, 0xc4, 0xb8, 0xd8, 0xdc, 0x12, 0x93, 0x4b, 0xf2, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xa0, 0x3c, 0x21, 0x09, 0x2e, 0x76, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26,
	0xb0, 0x04, 0x8c, 0xab, 0xe4, 0xc0, 0xc5, 0xe2, 0x96, 0x99, 0x93, 0x2a, 0x24, 0xc0, 0xc5, 0xec,
	0x9d, 0x5a, 0x09, 0xd5, 0x06, 0x62, 0x0a, 0x09, 0x71, 0xb1, 0xf8, 0xa6, 0x96, 0x24, 0x82, 0x35,
	0xf0, 0x04, 0x81, 0xd9, 0x20, 0x31, 0x97, 0xc4, 0x92, 0x44, 0x09, 0x66, 0x88, 0x18, 0x88, 0x6d,
	0xb4, 0x94, 0x91, 0x8b, 0x37, 0x0c, 0xec, 0xa4, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21,
	0x0b, 0x2e, 0xbe, 0xe0, 0x92, 0xa2, 0xd4, 0xc4, 0xdc, 0xe0, 0xd4, 0xbc, 0x14, 0xb0, 0xe9, 0xfc,
	0x7a, 0x70, 0x47, 0xeb, 0x81, 0x04, 0xa4, 0xd0, 0x05, 0x94, 0x18, 0x34, 0x18, 0x0d, 0x18, 0x85,
	0xf4, 0xb8, 0x38, 0x82, 0x52, 0x13, 0x89, 0xd6, 0x23, 0xa4, 0xc5, 0xc5, 0x12, 0x90, 0x99, 0x97,
	0x8e, 0xa2, 0x16, 0x14, 0x10, 0x52, 0xe8, 0x02, 0x4a, 0x0c, 0x49, 0x6c, 0xe0, 0xe0, 0x33, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xd2, 0x57, 0x14, 0x4e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VolumeServiceClient is the client API for VolumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VolumeServiceClient interface {
	StreamSendFile(ctx context.Context, opts ...grpc.CallOption) (VolumeService_StreamSendFileClient, error)
	ReadFile(ctx context.Context, in *File, opts ...grpc.CallOption) (*File, error)
	Ping(ctx context.Context, in *Pong, opts ...grpc.CallOption) (*Pong, error)
}

type volumeServiceClient struct {
	cc *grpc.ClientConn
}

func NewVolumeServiceClient(cc *grpc.ClientConn) VolumeServiceClient {
	return &volumeServiceClient{cc}
}

func (c *volumeServiceClient) StreamSendFile(ctx context.Context, opts ...grpc.CallOption) (VolumeService_StreamSendFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VolumeService_serviceDesc.Streams[0], "/volume_pb.VolumeService/StreamSendFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &volumeServiceStreamSendFileClient{stream}
	return x, nil
}

type VolumeService_StreamSendFileClient interface {
	Send(*File) error
	Recv() (*File, error)
	grpc.ClientStream
}

type volumeServiceStreamSendFileClient struct {
	grpc.ClientStream
}

func (x *volumeServiceStreamSendFileClient) Send(m *File) error {
	return x.ClientStream.SendMsg(m)
}

func (x *volumeServiceStreamSendFileClient) Recv() (*File, error) {
	m := new(File)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *volumeServiceClient) ReadFile(ctx context.Context, in *File, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/volume_pb.VolumeService/ReadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) Ping(ctx context.Context, in *Pong, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/volume_pb.VolumeService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeServiceServer is the server API for VolumeService service.
type VolumeServiceServer interface {
	StreamSendFile(VolumeService_StreamSendFileServer) error
	ReadFile(context.Context, *File) (*File, error)
	Ping(context.Context, *Pong) (*Pong, error)
}

func RegisterVolumeServiceServer(s *grpc.Server, srv VolumeServiceServer) {
	s.RegisterService(&_VolumeService_serviceDesc, srv)
}

func _VolumeService_StreamSendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VolumeServiceServer).StreamSendFile(&volumeServiceStreamSendFileServer{stream})
}

type VolumeService_StreamSendFileServer interface {
	Send(*File) error
	Recv() (*File, error)
	grpc.ServerStream
}

type volumeServiceStreamSendFileServer struct {
	grpc.ServerStream
}

func (x *volumeServiceStreamSendFileServer) Send(m *File) error {
	return x.ServerStream.SendMsg(m)
}

func (x *volumeServiceStreamSendFileServer) Recv() (*File, error) {
	m := new(File)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VolumeService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume_pb.VolumeService/ReadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).ReadFile(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pong)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume_pb.VolumeService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).Ping(ctx, req.(*Pong))
	}
	return interceptor(ctx, in, info, handler)
}

var _VolumeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "volume_pb.VolumeService",
	HandlerType: (*VolumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadFile",
			Handler:    _VolumeService_ReadFile_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _VolumeService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSendFile",
			Handler:       _VolumeService_StreamSendFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "volume.proto",
}
