// Code generated by protoc-gen-go. DO NOT EDIT.
// source: volume.proto

package volume_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_498b213ad3bcd5ad, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SyncFileList struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	FileList             []*File  `protobuf:"bytes,2,rep,name=FileList,proto3" json:"FileList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncFileList) Reset()         { *m = SyncFileList{} }
func (m *SyncFileList) String() string { return proto.CompactTextString(m) }
func (*SyncFileList) ProtoMessage()    {}
func (*SyncFileList) Descriptor() ([]byte, []int) {
	return fileDescriptor_498b213ad3bcd5ad, []int{1}
}

func (m *SyncFileList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncFileList.Unmarshal(m, b)
}
func (m *SyncFileList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncFileList.Marshal(b, m, deterministic)
}
func (m *SyncFileList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncFileList.Merge(m, src)
}
func (m *SyncFileList) XXX_Size() int {
	return xxx_messageInfo_SyncFileList.Size(m)
}
func (m *SyncFileList) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncFileList.DiscardUnknown(m)
}

var xxx_messageInfo_SyncFileList proto.InternalMessageInfo

func (m *SyncFileList) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *SyncFileList) GetFileList() []*File {
	if m != nil {
		return m.FileList
	}
	return nil
}

type Info struct {
	Action               string   `protobuf:"bytes,1,opt,name=Action,proto3" json:"Action,omitempty"`
	ErrorCode            string   `protobuf:"bytes,2,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_498b213ad3bcd5ad, []int{2}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Info) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *Info) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Info) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type File struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty"`
	ErrorCode            string   `protobuf:"bytes,3,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=ErrorMessage,proto3" json:"ErrorMessage,omitempty"`
	Meta                 []byte   `protobuf:"bytes,5,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_498b213ad3bcd5ad, []int{3}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *File) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *File) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *File) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *File) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "volume_pb.Empty")
	proto.RegisterType((*SyncFileList)(nil), "volume_pb.SyncFileList")
	proto.RegisterType((*Info)(nil), "volume_pb.Info")
	proto.RegisterType((*File)(nil), "volume_pb.File")
}

func init() { proto.RegisterFile("volume.proto", fileDescriptor_498b213ad3bcd5ad) }

var fileDescriptor_498b213ad3bcd5ad = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xeb, 0x50,
	0x10, 0xcd, 0x57, 0xfb, 0xda, 0x79, 0x79, 0x6d, 0x99, 0xc5, 0x7b, 0x21, 0xbc, 0x45, 0xb9, 0xab,
	0xa0, 0x10, 0xa4, 0x82, 0x74, 0x2b, 0x1a, 0x45, 0xb4, 0x20, 0x49, 0x11, 0x5c, 0xc9, 0x6d, 0x3b,
	0x96, 0x40, 0xf3, 0xc1, 0xcd, 0xb5, 0xd0, 0xbf, 0xe2, 0x8f, 0xf3, 0xb7, 0x48, 0x6e, 0x6b, 0x4c,
	0xab, 0xc5, 0xee, 0xce, 0x9c, 0x73, 0xe6, 0xce, 0xc9, 0x64, 0xc0, 0x5e, 0x66, 0x8b, 0x97, 0x84,
	0xfc, 0x5c, 0x64, 0x32, 0xc3, 0xf6, 0xba, 0x7a, 0xca, 0x27, 0xec, 0x17, 0x34, 0x82, 0x24, 0x97,
	0x2b, 0xf6, 0x08, 0x76, 0xb4, 0x4a, 0xa7, 0x57, 0xf1, 0x82, 0xee, 0xe2, 0x42, 0xe2, 0x7f, 0x68,
	0x8f, 0xe3, 0x84, 0x0a, 0xc9, 0x93, 0xdc, 0xd1, 0xfb, 0xba, 0xd7, 0x0e, 0x3f, 0x09, 0x3c, 0x86,
	0xd6, 0x87, 0xd3, 0x31, 0xfa, 0xa6, 0xf7, 0x7b, 0xd0, 0xf5, 0xab, 0x47, 0xfd, 0x52, 0x0a, 0x2b,
	0x03, 0x93, 0x60, 0xdd, 0xa4, 0xcf, 0x19, 0xfe, 0x85, 0xe6, 0xf9, 0x54, 0xc6, 0x59, 0xba, 0x79,
	0x6f, 0x53, 0x95, 0xa3, 0x02, 0x21, 0x32, 0x71, 0x91, 0xcd, 0xc8, 0x31, 0xd6, 0xa3, 0x2a, 0x02,
	0x19, 0xd8, 0xaa, 0x18, 0x51, 0x51, 0xf0, 0x39, 0x39, 0xa6, 0x32, 0x6c, 0x71, 0x88, 0x60, 0x5d,
	0x72, 0xc9, 0x1d, 0x4b, 0x69, 0x0a, 0xb3, 0x57, 0x1d, 0xac, 0x32, 0x02, 0xf6, 0xc0, 0xbc, 0xa5,
	0xd5, 0x66, 0x66, 0x09, 0x6b, 0x41, 0x8c, 0xfd, 0x41, 0xcc, 0x9f, 0x82, 0x58, 0xdf, 0x07, 0x19,
	0x91, 0xe4, 0x4e, 0xa3, 0xaf, 0x7b, 0x76, 0xa8, 0x70, 0x15, 0xae, 0xb9, 0xe6, 0x4a, 0x3c, 0x78,
	0x33, 0xe0, 0xcf, 0x83, 0xda, 0x57, 0x44, 0x62, 0x19, 0x4f, 0x09, 0x87, 0xd0, 0x89, 0xa4, 0x20,
	0x9e, 0x44, 0x94, 0xce, 0x54, 0xee, 0xdd, 0x8d, 0xba, 0xbb, 0x04, 0xd3, 0x3c, 0xfd, 0x44, 0x47,
	0x1f, 0x5a, 0x21, 0xf1, 0x83, 0x7b, 0x30, 0x80, 0xee, 0x35, 0xc9, 0xad, 0x9f, 0xfd, 0xaf, 0xe6,
	0xaa, 0x0b, 0xee, 0x3e, 0x81, 0x69, 0x38, 0x84, 0xde, 0x58, 0xf0, 0xb4, 0xe0, 0x6a, 0x77, 0x91,
	0xe4, 0x42, 0x62, 0xaf, 0x66, 0x57, 0x67, 0xe5, 0x7e, 0x61, 0x98, 0x86, 0x67, 0xd0, 0xa9, 0x75,
	0x06, 0xe9, 0xec, 0xc0, 0xbe, 0x23, 0xb0, 0xee, 0xe3, 0x74, 0xbe, 0xf5, 0x91, 0xe5, 0x61, 0xb9,
	0xbb, 0x04, 0xd3, 0x26, 0x4d, 0x75, 0xe9, 0xa7, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x06, 0x81,
	0xb2, 0xe1, 0xf9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VolumeServiceClient is the client API for VolumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VolumeServiceClient interface {
	StreamSendFile(ctx context.Context, opts ...grpc.CallOption) (VolumeService_StreamSendFileClient, error)
	ReadFile(ctx context.Context, in *File, opts ...grpc.CallOption) (*File, error)
	GetSyncFileList(ctx context.Context, in *SyncFileList, opts ...grpc.CallOption) (*SyncFileList, error)
	TransactionStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	TransactionEnd(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Ping(ctx context.Context, in *Info, opts ...grpc.CallOption) (*Info, error)
}

type volumeServiceClient struct {
	cc *grpc.ClientConn
}

func NewVolumeServiceClient(cc *grpc.ClientConn) VolumeServiceClient {
	return &volumeServiceClient{cc}
}

func (c *volumeServiceClient) StreamSendFile(ctx context.Context, opts ...grpc.CallOption) (VolumeService_StreamSendFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VolumeService_serviceDesc.Streams[0], "/volume_pb.VolumeService/StreamSendFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &volumeServiceStreamSendFileClient{stream}
	return x, nil
}

type VolumeService_StreamSendFileClient interface {
	Send(*File) error
	Recv() (*File, error)
	grpc.ClientStream
}

type volumeServiceStreamSendFileClient struct {
	grpc.ClientStream
}

func (x *volumeServiceStreamSendFileClient) Send(m *File) error {
	return x.ClientStream.SendMsg(m)
}

func (x *volumeServiceStreamSendFileClient) Recv() (*File, error) {
	m := new(File)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *volumeServiceClient) ReadFile(ctx context.Context, in *File, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/volume_pb.VolumeService/ReadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) GetSyncFileList(ctx context.Context, in *SyncFileList, opts ...grpc.CallOption) (*SyncFileList, error) {
	out := new(SyncFileList)
	err := c.cc.Invoke(ctx, "/volume_pb.VolumeService/GetSyncFileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) TransactionStart(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/volume_pb.VolumeService/TransactionStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) TransactionEnd(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/volume_pb.VolumeService/TransactionEnd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) Ping(ctx context.Context, in *Info, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := c.cc.Invoke(ctx, "/volume_pb.VolumeService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumeServiceServer is the server API for VolumeService service.
type VolumeServiceServer interface {
	StreamSendFile(VolumeService_StreamSendFileServer) error
	ReadFile(context.Context, *File) (*File, error)
	GetSyncFileList(context.Context, *SyncFileList) (*SyncFileList, error)
	TransactionStart(context.Context, *Empty) (*Empty, error)
	TransactionEnd(context.Context, *Empty) (*Empty, error)
	Ping(context.Context, *Info) (*Info, error)
}

func RegisterVolumeServiceServer(s *grpc.Server, srv VolumeServiceServer) {
	s.RegisterService(&_VolumeService_serviceDesc, srv)
}

func _VolumeService_StreamSendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VolumeServiceServer).StreamSendFile(&volumeServiceStreamSendFileServer{stream})
}

type VolumeService_StreamSendFileServer interface {
	Send(*File) error
	Recv() (*File, error)
	grpc.ServerStream
}

type volumeServiceStreamSendFileServer struct {
	grpc.ServerStream
}

func (x *volumeServiceStreamSendFileServer) Send(m *File) error {
	return x.ServerStream.SendMsg(m)
}

func (x *volumeServiceStreamSendFileServer) Recv() (*File, error) {
	m := new(File)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _VolumeService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume_pb.VolumeService/ReadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).ReadFile(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_GetSyncFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFileList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).GetSyncFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume_pb.VolumeService/GetSyncFileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).GetSyncFileList(ctx, req.(*SyncFileList))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_TransactionStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).TransactionStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume_pb.VolumeService/TransactionStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).TransactionStart(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_TransactionEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).TransactionEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume_pb.VolumeService/TransactionEnd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).TransactionEnd(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Info)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/volume_pb.VolumeService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).Ping(ctx, req.(*Info))
	}
	return interceptor(ctx, in, info, handler)
}

var _VolumeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "volume_pb.VolumeService",
	HandlerType: (*VolumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadFile",
			Handler:    _VolumeService_ReadFile_Handler,
		},
		{
			MethodName: "GetSyncFileList",
			Handler:    _VolumeService_GetSyncFileList_Handler,
		},
		{
			MethodName: "TransactionStart",
			Handler:    _VolumeService_TransactionStart_Handler,
		},
		{
			MethodName: "TransactionEnd",
			Handler:    _VolumeService_TransactionEnd_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _VolumeService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSendFile",
			Handler:       _VolumeService_StreamSendFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "volume.proto",
}
