// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package master_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type File struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Action               string   `protobuf:"bytes,2,opt,name=Action,proto3" json:"Action,omitempty"`
	ErrorCode            uint32   `protobuf:"varint,3,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	Node                 string   `protobuf:"bytes,4,opt,name=Node,proto3" json:"Node,omitempty"`
	Size                 uint32   `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Created              uint32   `protobuf:"varint,6,opt,name=Created,proto3" json:"Created,omitempty"`
	Meta                 []byte   `protobuf:"bytes,7,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Data                 []byte   `protobuf:"bytes,8,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *File) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *File) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *File) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *File) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetCreated() uint32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *File) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "master_pb.Empty")
	proto.RegisterType((*File)(nil), "master_pb.File")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbf, 0x4a, 0xc4, 0x40,
	0x10, 0xc6, 0x5d, 0x2f, 0x97, 0x98, 0xe1, 0x4e, 0x65, 0x0a, 0x19, 0xc4, 0x22, 0xa4, 0x4a, 0x15,
	0x44, 0x1b, 0x5b, 0x39, 0x4f, 0x10, 0xd1, 0x22, 0x79, 0x00, 0xd9, 0xbb, 0x4c, 0x11, 0x30, 0xb7,
	0x61, 0x1c, 0x84, 0xf3, 0xc9, 0x7c, 0x3c, 0xd9, 0x89, 0x7f, 0xc0, 0xee, 0xf7, 0xfd, 0xf6, 0xdb,
	0xe2, 0x1b, 0x58, 0x0c, 0xfe, 0x4d, 0x59, 0xea, 0x51, 0x82, 0x06, 0xcc, 0xa7, 0xf4, 0x32, 0x6e,
	0xca, 0x0c, 0xe6, 0xeb, 0x61, 0xd4, 0x7d, 0xf9, 0xe9, 0x20, 0xb9, 0xef, 0x5f, 0x19, 0x4f, 0x61,
	0xf6, 0xc8, 0x7b, 0x72, 0x85, 0xab, 0xf2, 0x26, 0x22, 0x9e, 0x41, 0x7a, 0xbb, 0xd5, 0x3e, 0xec,
	0xe8, 0xd0, 0xe4, 0x77, 0xc2, 0x0b, 0xc8, 0xd7, 0x22, 0x41, 0x56, 0xa1, 0x63, 0x9a, 0x15, 0xae,
	0x5a, 0x36, 0x7f, 0x02, 0x11, 0x92, 0xe7, 0xf8, 0x90, 0xd8, 0x1f, 0xe3, 0xe8, 0xda, 0xfe, 0x83,
	0x69, 0x6e, 0x65, 0x63, 0x24, 0xc8, 0x56, 0xc2, 0x5e, 0xb9, 0xa3, 0xd4, 0xf4, 0x4f, 0x8c, 0xed,
	0x27, 0x56, 0x4f, 0x59, 0xe1, 0xaa, 0x45, 0x63, 0x1c, 0xdd, 0x9d, 0x57, 0x4f, 0x47, 0x93, 0x8b,
	0x7c, 0xf5, 0x00, 0xcb, 0x69, 0x50, 0xcb, 0xf2, 0xde, 0x6f, 0x19, 0x6f, 0xe0, 0xb8, 0x55, 0x61,
	0x3f, 0xb4, 0xbc, 0xeb, 0x6c, 0xd4, 0x49, 0xfd, 0x3b, 0xb9, 0x8e, 0xe2, 0xfc, 0xbf, 0x28, 0x0f,
	0x2a, 0x77, 0xe9, 0x36, 0xa9, 0x1d, 0xe8, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x3f, 0x70,
	0x17, 0x30, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterServiceClient is the client API for MasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterServiceClient interface {
	StreamSendFile(ctx context.Context, opts ...grpc.CallOption) (MasterService_StreamSendFileClient, error)
}

type masterServiceClient struct {
	cc *grpc.ClientConn
}

func NewMasterServiceClient(cc *grpc.ClientConn) MasterServiceClient {
	return &masterServiceClient{cc}
}

func (c *masterServiceClient) StreamSendFile(ctx context.Context, opts ...grpc.CallOption) (MasterService_StreamSendFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MasterService_serviceDesc.Streams[0], "/master_pb.masterService/StreamSendFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &masterServiceStreamSendFileClient{stream}
	return x, nil
}

type MasterService_StreamSendFileClient interface {
	Send(*File) error
	Recv() (*File, error)
	grpc.ClientStream
}

type masterServiceStreamSendFileClient struct {
	grpc.ClientStream
}

func (x *masterServiceStreamSendFileClient) Send(m *File) error {
	return x.ClientStream.SendMsg(m)
}

func (x *masterServiceStreamSendFileClient) Recv() (*File, error) {
	m := new(File)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MasterServiceServer is the server API for MasterService service.
type MasterServiceServer interface {
	StreamSendFile(MasterService_StreamSendFileServer) error
}

func RegisterMasterServiceServer(s *grpc.Server, srv MasterServiceServer) {
	s.RegisterService(&_MasterService_serviceDesc, srv)
}

func _MasterService_StreamSendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MasterServiceServer).StreamSendFile(&masterServiceStreamSendFileServer{stream})
}

type MasterService_StreamSendFileServer interface {
	Send(*File) error
	Recv() (*File, error)
	grpc.ServerStream
}

type masterServiceStreamSendFileServer struct {
	grpc.ServerStream
}

func (x *masterServiceStreamSendFileServer) Send(m *File) error {
	return x.ServerStream.SendMsg(m)
}

func (x *masterServiceStreamSendFileServer) Recv() (*File, error) {
	m := new(File)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MasterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "master_pb.masterService",
	HandlerType: (*MasterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSendFile",
			Handler:       _MasterService_StreamSendFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "master.proto",
}
